server:
  port: 5001
spring:
  data:
    mongodb:
      host: mymongodb
      port: 27017
      database: clientBank
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
          defaultZone: http://eureka-service:8761/eureka