server:
  port: 5004
spring:
  data:
    mongodb:
      host: mymongodb
      port: 27017
      database: creditBank
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
          defaultZone: http://eureka-service:8761/eureka
resilience4j.circuitbreaker:
    instances:
        DepositCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10