server:
  port: 5005
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: movementBank
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka