server:
  port: 8081
spring:
  cloud:
      config:
          server:
            git:
              default-label: config-data
              uri: https://github.com/RECAVERO/proyecto01/
              search-paths: config-data
  application:
    name: config-service
