server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-docker
          uri: https://github.com/RECAVERO/proyecto03/
          search-paths: config-data
  application:
    name: config-service

